#!/usr/bin/with-contenv bashio
# ==============================================================================
# Generate /etc/crontabs/root from addon options (powerslider fork).
# Runs once before services.d — standard HA addon cont-init.d pattern.
#
# Reads options directly via jq on /data/options.json (not bashio::config)
# because bashio::config requires a working Supervisor API and fails silently
# in off-HA environments (our local test harness). jq-direct is portable and
# produces identical results in production.
#
# Options consumed:
#   PollIntervalDay   (1-30, minutes)       default 5
#   PollIntervalNight (0-60, 0 = disabled)  default 0
#   DayStart          (0-23, hour)          default 6
#   DayEnd            (1-23, hour)          default 22
#   EnableUpload      (bool)                default true
#
# Every SBFspot invocation is wrapped in flock(1) on /run/sbfspot.lock to
# prevent overlapping BT sessions (B5 upstream bug).
# ==============================================================================
set -euo pipefail

readonly OPTIONS=/data/options.json

if [[ ! -f "${OPTIONS}" ]]; then
    bashio::log.fatal "Addon options file missing: ${OPTIONS}"
    exit 1
fi

# Read option with fallback when key is missing OR value is null.
# Usage: opt_or <key> <default>
#
# NOTE: jq's `//` operator treats `false` as "missing", which would wrongly
# substitute the default for a bool option set to false. We use an explicit
# null check so that `EnableUpload: false` survives intact.
opt_or() {
    local key="${1}" default="${2}"
    local value
    value=$(jq -r --arg k "${key}" 'if .[$k] == null then empty else .[$k] end' \
        "${OPTIONS}" 2>/dev/null || true)
    # Treat empty string (missing key) as "use default", but keep "false".
    if [[ -z "${value}" ]]; then
        printf '%s' "${default}"
    else
        printf '%s' "${value}"
    fi
}

POLL_DAY=$(opt_or PollIntervalDay 5)
POLL_NIGHT=$(opt_or PollIntervalNight 0)
DAY_START=$(opt_or DayStart 6)
DAY_END=$(opt_or DayEnd 22)
ENABLE_UPLOAD=$(opt_or EnableUpload true)
# V2-03: 0 = auto (PollIntervalDay*60-10), else explicit override
SBF_TIMEOUT_OVERRIDE=$(opt_or SBFspotTimeoutSec 0)

# Clamp to documented ranges defensively. Schema rejects out-of-range on save
# but treat this as belt-and-braces for migrations / malformed overrides.
(( POLL_DAY   < 1  )) && POLL_DAY=1
(( POLL_DAY   > 30 )) && POLL_DAY=30
(( POLL_NIGHT < 0  )) && POLL_NIGHT=0
(( POLL_NIGHT > 60 )) && POLL_NIGHT=60
(( DAY_START  < 0  )) && DAY_START=0
(( DAY_START  > 23 )) && DAY_START=23
(( DAY_END    < 1  )) && DAY_END=1
(( DAY_END    > 23 )) && DAY_END=23
if (( DAY_START >= DAY_END )); then
    bashio::log.warning "DayStart (${DAY_START}) >= DayEnd (${DAY_END}), forcing 6-22"
    DAY_START=6
    DAY_END=22
fi

readonly SBF=/usr/bin/sbfspot/SBFspot
readonly UPLOAD_DAEMON=/usr/bin/sbfspot/SBFspotUploadDaemon
readonly UPLOAD_CFG=/usr/bin/sbfspot/SBFspotUpload.cfg

# Overlap prevention: cap each SBFspot invocation at (POLL_DAY*60 - 10) seconds
# so it hard-kills before the next poll tick. Previous approach (`flock -n
# /run/sbfspot.lock`) turned out to silently block all subsequent runs when a
# single SBFspot call hung (observed 8+ min hangs after Logon OK). `timeout` is
# preferred: each tick has a fresh slate, no stale locks. Cost: overlap at the
# boundary if a run times out exactly as the next starts, but that's a one-off
# failed-run, self-healing at the next tick.
#
# BusyBox `timeout -s KILL <secs>` sends SIGKILL after the timeout. 10s buffer
# leaves time for BT-session cleanup before next tick fires.
# V2-03: user override vs auto-derived cap
if (( SBF_TIMEOUT_OVERRIDE > 0 )); then
    SBF_TIMEOUT=${SBF_TIMEOUT_OVERRIDE}
else
    SBF_TIMEOUT=$(( POLL_DAY * 60 - 10 ))
    (( SBF_TIMEOUT < 30 )) && SBF_TIMEOUT=30
fi
readonly SBF_WRAPPED="timeout -s KILL ${SBF_TIMEOUT} ${SBF}"

DAY_HOURS="${DAY_START}-${DAY_END}"

# Night window wraps midnight. Examples:
#   DayStart=6, DayEnd=22 → night = 23-23,0-5
#   DayStart=0, DayEnd=22 → night = 23-23
#   DayStart=6, DayEnd=23 → night = 0-5
#   DayStart=0, DayEnd=23 → no night window (no polling possible)
NIGHT_HOURS=""
if (( DAY_END < 23 )) && (( DAY_START > 0 )); then
    NIGHT_HOURS="$((DAY_END + 1))-23,0-$((DAY_START - 1))"
elif (( DAY_END < 23 )); then
    NIGHT_HOURS="$((DAY_END + 1))-23"
elif (( DAY_START > 0 )); then
    NIGHT_HOURS="0-$((DAY_START - 1))"
fi

{
    echo "SHELL=/bin/bash"
    echo "# Generated by 01-generate-crontab.sh — source of truth is addon options"
    echo ""
    echo "# One-shot publish on container boot (ad0 = today only)"
    echo "@reboot sleep 30 && ${SBF_WRAPPED} -v -ad0 -am0 -mqtt -finq > /dev/stdout"
    echo ""
    echo "# Daytime polling: every ${POLL_DAY} min, hours ${DAY_HOURS}, timeout ${SBF_TIMEOUT}s"
    echo "*/${POLL_DAY} ${DAY_HOURS} * * *    ${SBF_WRAPPED} -v -ad1 -am0 -ae0 -mqtt > /dev/stdout"

    if (( POLL_NIGHT > 0 )) && [[ -n "${NIGHT_HOURS}" ]]; then
        echo ""
        echo "# Nighttime polling: every ${POLL_NIGHT} min, hours ${NIGHT_HOURS}"
        # Night cap: poll_night*60-10 (same logic), floor 30
        NIGHT_TIMEOUT=$(( POLL_NIGHT * 60 - 10 ))
        (( NIGHT_TIMEOUT < 30 )) && NIGHT_TIMEOUT=30
        echo "*/${POLL_NIGHT} ${NIGHT_HOURS} * * *   timeout -s KILL ${NIGHT_TIMEOUT} ${SBF} -v -ad0 -am0 -mqtt > /dev/stdout"
    fi

    echo ""
    echo "# Daily archive poll at 05:55 (14-day catch-up, 5-min hard cap)"
    echo "55 05 * * *   timeout -s KILL 300 ${SBF} -v -sp0 -ad14 -am1 -ae1 -mqtt -finq > /dev/stdout"

    if [[ "${ENABLE_UPLOAD,,}" == "true" ]]; then
        echo ""
        echo "# PVOutput uploader (background daemon, restarts on @reboot)"
        echo "@reboot sleep 60 && ${UPLOAD_DAEMON} -c ${UPLOAD_CFG} > /dev/stdout"
    fi

    echo ""
    echo "# Log tail heartbeat (keeps HA log visible during idle)"
    echo "*/${POLL_DAY} ${DAY_HOURS} * * *   /usr/bin/sbfspot/taillog.sh"
} > /etc/crontabs/root

chmod 600 /etc/crontabs/root

bashio::log.info "Crontab generated:"
bashio::log.info "  day poll   : every ${POLL_DAY} min, hours ${DAY_HOURS}"
if (( POLL_NIGHT > 0 )) && [[ -n "${NIGHT_HOURS}" ]]; then
    bashio::log.info "  night poll : every ${POLL_NIGHT} min, hours ${NIGHT_HOURS}"
else
    bashio::log.info "  night poll : disabled"
fi
if [[ "${ENABLE_UPLOAD,,}" == "true" ]]; then
    bashio::log.info "  upload     : enabled"
else
    bashio::log.info "  upload     : disabled"
fi
if (( SBF_TIMEOUT_OVERRIDE > 0 )); then
    bashio::log.info "  SBFspot cap: ${SBF_TIMEOUT}s (explicit override), 300s (archive)"
else
    bashio::log.info "  SBFspot cap: ${SBF_TIMEOUT}s (auto = day_poll-10), 300s (archive)"
fi
